### ISSUE TITLE
[BUG] DivideByZero error on progress command

### ISSUE THREAD

**Issue by TurnrDev** [TrainerDex/DiscordBot#11]
**Describe the bug**
```
Exception in command 'progress'
Traceback (most recent call last):
  File "/opt/DiscordBot/env/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/opt/DiscordBot/tdx/core.py", line 303, in progress
    embed = await self.build_UpdatedProfileCard(ctx, trainer)
  File "/opt/DiscordBot/tdx/core.py", line 77, in build_UpdatedProfileCard
    return await UpdatedProfileCard(trainer, **kwargs).build_card(self, ctx)
  File "/opt/DiscordBot/tdx/embeds.py", line 135, in build_card
    self.add_field(name=_("Daily XP Gain"), value=_("{gain}/day").format(gain=cf.humanize_number(round(stat_delta/days))))
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/DiscordBot/env/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/DiscordBot/env/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/DiscordBot/env/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ZeroDivisionError: division by zero
```

**To Reproduce**
1. Run `progress `command
2. See error

**Expected behavior**
No DivideByZero bug

**Additional context**
Probably related to your bad code which gets the previous update

**Comment by TurnrDev** [comment]
Fixed in 923f5ced3264d7848ebdff50a971106e0767f108
